version: '3.8'

services:

  fpm:
    build:
      context: .
      dockerfile: Containerfile_PHP-FPM
    container_name: php-fpm
    tty: true
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - '9003:9003'  # Xdebug向け
    depends_on:
      - db

  web:
    image: docker.io/library/nginx:latest
    container_name: nginx
    tty: true
    ports:
      - '8000:80'
    volumes:
      - ./htdocs:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm

  db:
    image: docker.io/mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    privileged: true
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mochiuchat
      MYSQL_DATABASE: chatdb
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
